# Know Issues:
# Cursor ist weird:
# desktop file anpassen, damit alacritty mit x11 geoffnet wird
# sudo vim ./usr/share/applications/Alacritty.desktop
# dann Exec line aendern:
# Exec=env WAYLAND_DISPLAY= alacritty 

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
# normal contrast background = '#282828'
# soft contrast background = = '#32302f'
background = '#1d2021'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'
#white   = '#ebdbb2'
#white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors.cursor]
text    = '#000000'
cursor  = '#f8f8f2'

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[font]
size = 12

[font.normal]
family = "0xProto Nerd Font Mono"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
startup_mode = "Maximized"

[keyboard]
bindings = [
  { key = "Back", mods = "Alt", chars = "\u0017"},
  { key = "Back", mods = "Control", chars = "\u0017"},
]

